First commit for test
yakovlevkl/qa_java pull request #9
Opened 2021-11-27 04:32 UTC by yakovlevkl

2021-11-28 18:19 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
>          }
В тексте Exception орфографическая ошибка

Так же, обрати внимание - лучше создавать кастомное исключение, которое уже своим названием описывает суть ошибки.

Например, в данном случае - InvalidSexName вполне бы подошло)

2021-11-28 18:19 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
>          return feline.getKittens();
Параметр number не используется в методе

2021-11-28 18:20 UTC, NickFlexer commented on src/test/java/com/example/AlexMockTest.java
> +    Alex alex;
Где в коде задается класс Alex?

2021-11-28 18:21 UTC, NickFlexer commented on src/main/java/com/example/Feline.java
>          return getKittens(1);
При вызове этого метода без параметров всегда возвращается значение 1. Правильно ли это? У всех кошачьих всегда 1 котенок?)

2021-11-28 18:22 UTC, NickFlexer requested changes
Добрый день!

Пока возвращаю на доработку.
В коде нет описания класса Alex, но есть тесты на него. Это нужно исправить.

2021-11-29 07:48 UTC, yakovlevkl commented on src/main/java/com/example/Lion.java
>          }
Эта ошибка допущена создателем метода. 
На деле надо баг репорт создать на автора.
В контексте проекта, я обрабатываю текст эксепшена как есть, предполагая, что это задумка автора.

2021-11-29 07:49 UTC, yakovlevkl commented on src/test/java/com/example/AlexMockTest.java
> +    Alex alex;
Странно, класс не запушился... Исправил.

2021-11-29 07:51 UTC, yakovlevkl commented on src/main/java/com/example/Feline.java
>          return getKittens(1);
Этот метод создан автором, какова его задумка мне неизвестно.)
На деле надо баг репорт создать на автора.
В контексте проекта, тестируем его как есть.

2021-12-01 12:47 UTC, NickFlexer commented on src/main/java/com/example/Lion.java
>          }
Обычно при работе с кодом нужно придерживаться правила бой-скаутов - https://techrocks.ru/2018/07/14/10-golden-rules-for-programmers/

Если видишь плохой код, исправь его)

2021-12-01 12:48 UTC, NickFlexer commented on src/main/java/com/example/Feline.java
>          return getKittens(1);
То же самое, ты уже работаешь с кодом. Если задумка не понятно, стоит исправить так, чтобы код был читаемым и поддерживаемым.

2021-12-01 12:48 UTC, NickFlexer approved these changes
Добрый день!

Я готов поставить зачет, спасибо за доработку!

2021-12-01 13:26 UTC, merged